export const GET_EMPLOYEE_URL = '/api/employee/getEmployee';
export const CREATE_EMPLOYEE_URL = '/api/employee/createEmployee';
export const DELETE_EMPLOYEE_URL = '/api/employee/deleteEmployee';
export const UPDATE_EMPLOYEE_URL = '/api/employee/updateEmployee';
export const DOWNLOAD_EMPLOYEE_URL = '/api/employee/downloadEmployee';
export const REGISTER_URL = '/api/user/register'; // 注册用户的接口
export const USERNAMELOGIN_URL = '/api/user/login'; // 用户名密码登录接口
export const EMAILLOGIN_URL = '/api/user/loginByEmail'; // 邮箱验证码登录接口
export const SENDLOGINVC_URL = '/api/user/sendLoginVerifyCode'; // 发送登录验证码接口
export const SENDREGISTERVC_URL = '/api/user/sendRegisterVerifyCode'; // 发送注册验证码接口
export const INIT = '/api/user/init'; // 获取token的接口
export const LOGOUT = '/api/user/logout'; // 退出登录的接口