export const GET_EMPLOYEE_URL = '/soul-harbor/api/employee/getEmployee';
export const CREATE_EMPLOYEE_URL = '/soul-harbor/api/employee/createEmployee';
export const DELETE_EMPLOYEE_URL = '/soul-harbor/api/employee/deleteEmployee';
export const UPDATE_EMPLOYEE_URL = '/soul-harbor/api/employee/updateEmployee';
export const DOWNLOAD_EMPLOYEE_URL = '/soul-harbor/api/employee/downloadEmployee';

export const REGISTER_URL = '/soul-harbor/api/user/register'; // 注册用户的接口
export const USERNAMELOGIN_URL = '/soul-harbor/api/user/login'; // 用户名密码登录接口
export const EMAILLOGIN_URL = '/soul-harbor/api/user/loginByEmail'; // 邮箱验证码登录接口
export const SENDLOGINVC_URL = '/soul-harbor/api/user/sendLoginVerifyCode'; // 发送登录验证码接口
export const SENDREGISTERVC_URL = '/soul-harbor/api/user/sendRegisterVerifyCode'; // 发送注册验证码接口
export const SENDFORGETPASSWORD_LINK = '/soul-harbor/api/user/forgetPassword'; // 发送「忘记密码」验证链接接口
export const CHECKTOKENVALID = '/soul-harbor/api/user/checkTokenValid'; // 检查「忘记密码」重置链接是否有效接口
export const UPDATEPASSWORD = '/soul-harbor/api/user/updatePassword'; // 重设密码接口
export const INIT = '/soul-harbor/api/user/init'; // 获取token的接口
export const XSRFINIT = '/soul-harbor/api/user/xsrf'; // 设置xsrfToken
export const LOGOUT = '/soul-harbor/api/user/logout'; // 退出登录的接口
export const UPLOADAVATAR = '/soul-harbor/api/user/avatar-upload'; // 上传用户头像的接口
export const BASICINFO = '/soul-harbor/api/user/basic-info'; // 修改用户基础信息的接口

export const UPLOADCHUNK = '/soul-harbor/api/file/uploadChunks'; // 上传文件的接口
export const MERGECHUNK = '/soul-harbor/api/file/mergeChunks'; // 合并文件的接口
export const CHECKCHUNK = '/soul-harbor/api/file/verifyChunks'; // 验证文件的接口

export const SEARCH_MEMBER = '/soul-harbor/api/chat/search'; // 聊天搜索用户的接口
export const GET_UNREAD_MSG = '/soul-harbor/api/chat/unread'; // 查看未读信息
export const GET_FRIENDS_LIST = '/soul-harbor/api/chat/getFriendsList'; // 查看好友列表
export const GET_SESSIONS_LIST = '/soul-harbor/api/chat/getSessionsList'; // 查看会话列表
export const ADD_FRIEND = '/soul-harbor/api/chat/addFriend'; // 添加好友
export const GET_HISTORY_MSG = '/soul-harbor/api/chat/getHisMsg'; // 获取某个回话的历史信息
export const READ_UNREAD_MSG = '/soul-harbor/api/chat/readUnreadMsg'; // 查阅未读信息
export const ROBOT_CHAT = '/soul-harbor/api/chat/robotChat'; // 机器人聊天
export const NEW_GROUP_CHAT = '/soul-harbor/api/chat/newGroupChat'; // 新建群聊
export const GET_GROUPS_LIST = '/soul-harbor/api/chat/getGroupsList'; // 获取群列表
export const GET_GROUP_MEMBERS = '/soul-harbor/api/chat/getGroupMembers'; // 获取群成员列表
export const ADD_GROUP_MEMBERS = '/soul-harbor/api/chat/addGroupMembers'; // 添加群成员
export const EXIT_GROUP = '/soul-harbor/api/chat/exitGroup'; // 退出群聊
export const DELETE_GROUP_MEMBER = '/soul-harbor/api/chat/deleteMember'; // 删除群成员
export const GET_SESSION_INFO = '/soul-harbor/api/chat/getSessionInfo'; // 拉取某个会话信息
export const DELETE_FRIEND = '/soul-harbor/api/chat/deleteFriend'; // 删除好友
export const SEARCH_CONTRACTS = '/soul-harbor/api/chat/searchContracts'; // 查找联系人
export const SEARCH_CHAT_RECORDS = '/soul-harbor/api/chat/searchChatRecords'; // 查找聊天记录
